### ISSUE TITLE
Kali linux problem

### ISSUE THREAD

**Issue by eudomoniacc** [Dfte/Discovery#3]
raceback (most recent call last):
  File "/usr/lib/python3.7/sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "discovery.py", line 22, in <module>
    import pythonwhois
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois-2.4.3-py3.7.egg/pythonwhois/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois-2.4.3-py3.7.egg/pythonwhois/parse.py", line 363, in <module>
    - 1.8.3 Add regex_group_count to with_pattern() decorator to support
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois-2.4.3-py3.7.egg/pythonwhois/parse.py", line 363, in <listcomp>
    - 1.8.3 Add regex_group_count to with_pattern() decorator to support
  File "/usr/local/lib/python3.7/dist-packages/pythonwhois-2.4.3-py3.7.egg/pythonwhois/parse.py", line 205, in preprocess_regex
    Some notes for the date and time types:
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.7/sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0
 here is the output

**Comment by Dfte** [comment]
Hi, well first sorry for not answering sooner... The project is actually getting reworked and will be released on another Github. So for the moment i will not correct the actual version bugs. However i'll let this issue opened to link you the new version which will probably be released in a couple of months :)

Good evening !

**Comment by Dfte** [comment]
Oh by the way, this is not a problem related to Discovery, it is related to a change made by the Python developpers between version 3.5/6 and 3.7. I guess tha author of the re module will push a fix for python 3.7 in a few days :)
